bin: drop umlaut again for setuptools
setuptools cannot handle non-ascii characters in files declared in
"scripts".

$ python setup.py develop

  [snip]

  File "setuptools/command/easy_install.py", line 726, in process_distribution
    self.install_egg_scripts(dist)
  File "setuptools/command/develop.py", line 188, in install_egg_scripts
    self.install_script(dist, script_name, script_text, script_path)
  File "setuptools/command/easy_install.py", line 805, in install_script
    self.write_script(script_name, _to_ascii(script_text), 'b')
  File "setuptools/command/easy_install.py", line 108, in _to_ascii
    return s.encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 785: ordinal not in range(128)

Commit 4424008f6aaa7ce93d02f0c4948ad50542284ece fixed this, and
23874c2c50ebd57426797d38f4f9c6c40dc336ec added the umlaut back in. Take
it out again so "setup.py develop" and "setup.py install" succeeds
again.

See https://github.com/pypa/setuptools/issues/761

Signed-off-by: Guido Günther <agx@sigxcpu.org>