GitRepository: use stdout as last resort if stderr is empty
This e.g. gives:

    GitRepositoryError: Error running git commit: On branch master
    Untracked files:
	debian/

    nothing added to commit but untracked files present

Instead of

    GitRepositoryError: Error running git commit: