d/control: Specify required git version as dependency
Explicitly specify the git version to facilitate easier backporting.
Developers can align with this git version to reduce false alarms due
to version inconsistencies.

The latest git-buildpackage requires a newer git version to avoid test
failures. For example, building the source in bookworm with git 1:2.39.2-1.1
results in:

$ ./packaging/run-in-docker -t bookworm

    FAIL: Doctest: tests.doctests.test_GitRepository.test_clone
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3.11/doctest.py", line 2222, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
    AssertionError: Failed doctest test for test_clone
      File "/workdir/project/tests/doctests/test_GitRepository.py", line 626, in test_clone

    ----------------------------------------------------------------------
    File "/workdir/project/tests/doctests/test_GitRepository.py", line 649, in test_clone
    Failed example:
    clone.get_remote_branches()
    Expected:
    ['origin', 'origin/foo', 'origin/master']
    Got:
    ['origin/HEAD', 'origin/foo', 'origin/master']

    -------------------- >> begin captured logging << --------------------
    gbp: debug: ['git', 'rev-parse', '--show-cdup']
    gbp: debug: ['git', 'rev-parse', '--is-bare-repository']
    gbp: debug: ['git', 'rev-parse', '--git-dir']
    gbp: debug: ['git', 'symbolic-ref', 'HEAD']
    gbp: debug: ['git', 'show-ref', 'refs/heads/master']
    gbp: debug: ['git', 'clone', '--quiet', '/tmp/tmp72nxjjwzgbp_tests.doctests.test_GitRepository_/repo']
    gbp: debug: ['git', 'rev-parse', '--show-cdup']
    gbp: debug: ['git', 'rev-parse', '--is-bare-repository']
    gbp: debug: ['git', 'rev-parse', '--git-dir']
    gbp: debug: ['git', 'for-each-ref', '--format=%(refname:short)', 'refs/heads/']
    gbp: debug: ['git', 'symbolic-ref', 'HEAD']
    gbp: debug: ['git', 'show-ref', 'refs/heads/master']
    gbp: debug: ['git', 'for-each-ref', '--format=%(refname:short)', 'refs/remotes/']
    gbp: debug: ['git', 'for-each-ref', '--format=%(refname:short)', 'refs/heads/']
    gbp: debug: ['git', 'config', 'branch.master.remote']
    gbp: debug: ['git', 'config', 'branch.master.merge']
    gbp: debug: ['git', 'branch', 'foo', 'origin/foo']
    gbp: debug: ['git', 'config', 'branch.foo.remote']
    gbp: debug: ['git', 'config', 'branch.foo.merge']
    gbp: debug: ['git', 'branch', 'bar']
    gbp: debug: ['git', 'config', 'branch.bar.remote']
    gbp: debug: ['git', 'for-each-ref', '--format=%(refname:short)', 'refs/heads/']
    gbp: debug: ['git', 'remote']
    gbp: debug: ['git', 'remote']
    gbp: debug: ['git', 'remote', 'show', '-n', 'origin']
    gbp: debug: ['git', 'show-ref', '--verify', 'refs/remotes/origin/master']
    gbp: debug: ['git', 'remote']
    gbp: debug: ['git', 'remote', 'show', '-n', 'origin']
    --------------------- >> end captured logging << ---------------------